In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [ ]:
true = pd.read_csv("Fake.csv")
true["outcome"] = "Fake"
false = pd.read_csv("True.csv")
false["outcome"] = "True"
all = pd.concat([true, false])
all = all.sample(frac = 1, random_state = 1).reset_index(drop = True)
all.head()

,title,text,subject,date,outcome
0,Trump Calls For This Racist Policy To Be Forc...,Donald Trump is calling for one of the most co...,News,"September 21, 2016",Fake
1,Republican ex-defense secretary Cohen backs Hi...,WASHINGTON (Reuters) - Former Republican U.S. ...,politicsNews,"September 7, 2016",True
2,"TEACHER QUITS JOB After 5th, 6th Grade Muslim ...",You re never to young to commit jihad Teachers...,politics,"May 9, 2017",Fake
3,LAURA INGRAHAM RIPS INTO THE PRESS…Crowd Goes ...,Laura Ingraham reminds the Never Trump people ...,politics,"Jul 21, 2016",Fake
4,Germany's Merkel suffers state vote setback as...,BERLIN/HANOVER (Reuters) - Germany s Social De...,worldnews,"October 14, 2017",True

In [ ]:
all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44898 entries, 0 to 44897
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    44898 non-null  object
 1   text     44898 non-null  object
 2   subject  44898 non-null  object
 3   date     44898 non-null  object
 4   outcome  44898 non-null  object
dtypes: object(5)
memory usage: 1.7+ MB

In [ ]:
all = all.drop(columns = ["subject", "date"])
all.head()

,title,text,outcome
0,Trump Calls For This Racist Policy To Be Forc...,Donald Trump is calling for one of the most co...,Fake
1,Republican ex-defense secretary Cohen backs Hi...,WASHINGTON (Reuters) - Former Republican U.S. ...,True
2,"TEACHER QUITS JOB After 5th, 6th Grade Muslim ...",You re never to young to commit jihad Teachers...,Fake
3,LAURA INGRAHAM RIPS INTO THE PRESS…Crowd Goes ...,Laura Ingraham reminds the Never Trump people ...,Fake
4,Germany's Merkel suffers state vote setback as...,BERLIN/HANOVER (Reuters) - Germany s Social De...,True

In [ ]:
# TODO:
# - remove CITY (Source) from True texts
# - remove the course from Fake titles

In [ ]:
X = ["title", "text"]
y = "outcome"

In [ ]:
X_train_val, X_test, y_train_val, y_test = train_test_split(all[X], all[y], test_size = 1 / 10, random_state = 1, shuffle = True)
X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size = 1 / 9, random_state = 1, shuffle = True)

In [ ]:
X_train.to_csv("X_train.csv")
X_val.to_csv("X_val.csv")
X_test.to_csv("X_test.csv")

y_train.to_csv("y_train.csv")
y_val.to_csv("y_val.csv")
y_test.to_csv("y_test.csv")